### ISSUE TITLE
Does not compile with latexmk due to fontspec and minted

### ISSUE THREAD

**Issue by miguel-negrao** [joseareia/ipleiria-thesis#3]
This repository does not compile with the `latexmk` command since it requires xelatex or lualatex and minted requires `--shell-escape`.

I suggest adding the following `.latexmkrc` configuration file:

```
#!/bin/env perl

# PDF-generating modes are:
# 1: pdflatex, as specified by $pdflatex variable (still largely in use)
# 2: postscript conversion, as specified by the $ps2pdf variable (useless)
# 3: dvi conversion, as specified by the $dvipdf variable (useless)
# 4: lualatex, as specified by the $lualatex variable (best)
# 5: xelatex, as specified by the $xelatex variable (second best)
$pdf_mode = 5;

# --shell-escape option (execution of code outside of latex) is required for the
#'minted' package.
#
# SyncTeX allows to jump between source (code) and output (PDF) in IDEs with support
# (many have it). A value of `1` is enabled (gzipped), `-1` is enabled but uncompressed,
# `0` is off.
# Testing in VSCode w/ LaTeX Workshop only worked for the compressed version.
# Adjust this as needed. Of course, only relevant for local use, no effect on a remote
# CI pipeline (except for slower compilation, probably).
#
# %O and %S will forward Options and the Source file, respectively, given to latexmk.
#
# `set_tex_cmds` applies to all *latex commands (latex, xelatex, lualatex, ...), so
# no need to specify these each. This allows to simply change `$pdf_mode` to get a
# different engine. Check if this works with `latexmk --commands`.
set_tex_cmds("--shell-escape --synctex=1 %O %S");

$root_filename = 'IPleiriaMain.tex';
```

Currently due to #2 it still won't compile, but perhaps when that is fixed this will work.

**Comment by joseareia** [comment]
Hello @miguel-negrao!

Thank you _once again_ for reporting this issue. As mentioned in issue #2, I'll review it and aim to have a resolution in the coming days.

**Comment by joseareia** [comment]
As mentioned in #2, the compilation issue has been resolved. The `minted` problem was fixed with the configuration file you provided (**thank you for that**), and the `fontspec` error can now be resolved by installing the **TeXGyre Fonts**, as outlined in the README:

```
sudo apt install fonts-texgyre
```

Let me know if everything works as expected now!

**Comment by miguel-negrao** [comment]
It now compiles with `latexmk`  , thanks for the change. 

Out of curiosity, why use rubber instead of latexmk ? I had a sense that latexmk is the most used compilation system for latex, and for instance vscode latex workshop will use latexmk, so with your latest changes it will (almost) work out of the box in vscode by selecting "recipe: latexmk (latexmkrc)".

**Comment by joseareia** [comment]
It’s true that `latexmk` is the most widely used compilation system. However, as [Stéphane Caron](https://scaron.info/) (creator of `rubber`) points out, "_LaTeX errors sometimes put this tool (latexmk) in an inconsistent state, requiring a Ctrl-C and restart to update the PDF correctly_" ([source](https://scaron.info/blog/makefiles-for-latex.html#addendum)).

That said, since the [`.latexmkrc`](https://github.com/joseareia/ipleiria-thesis/blob/master/.latexmkrc) file is available, one can simply compile using it. I'm not against using `latexmk`; if it improves the workflow, I’m open to making the change!

**Comment by miguel-negrao** [comment]
It's fine with me to have support for both. Feel free to close this issue. Thanks !
